### PR TITLE
Implemented glowing item frames

### PR DESCRIPTION
**Pull request by DerEnderKeks**
I also auto formatted everything to get rid of the lines that only contained spaces..

### CODE REVIEW

**Comment by SydMontague** [comment]
Please don't autoformat, it makes it very hard to read the diffs.

**Comment by DerEnderKeks** [comment]
I split it up into 2 commits for that reason, seems easy enough to read to me.

**Comment by SydMontague** [comment]
The problem is that I still have to look over it and that my own autoformatter will revert these changes anyways. It also touches more files than necessary, making merge issues more likely.

Anyways, nonetheless good work and thanks for the PR, I appreciate it. :)

**Comment by DerEnderKeks** [comment]
Thanks :D

Just curious: What IDE are you using and why does it leave spaces at the end of lines? :P

**Comment by SydMontague** [comment]
I use Eclipse and I probably set it this way to not get thrown back to start of lines when navigating through the code—for empty lines that is, for trailing spaces I probably just forgot pressing the autoformatter. :S

**Pull request merged**
